//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int Product_name { get; set; }
        public int numberofprocess { get; set; }
        public string listofprocessname { get; set; }
        public string listoflabourers { get; set; }
        public string listofmachineid { get; set; }
    
        public virtual product_name product_name1 { get; set; }
        public virtual User_list User_list { get; set; }
    }
}
