//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_process
    {
        public int ID { get; set; }
        public Nullable<int> Actual_Qt { get; set; }
        public Nullable<int> Req_Qt { get; set; }
        public Nullable<int> Process_type { get; set; }
        public Nullable<int> Lat_Emp_workOn { get; set; }
        public Nullable<int> Current_Emp_workOn { get; set; }
    
        public virtual Material_ontrack Material_ontrack { get; set; }
        public virtual User_list User_list { get; set; }
        public virtual User_list User_list1 { get; set; }
    }
}
