//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechine_status
    {
        public int ID { get; set; }
        public int MechID { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public int LabourID { get; set; }
        public bool IsDown { get; set; }
        public Nullable<int> active_range { get; set; }
    
        public virtual Mechines_cat Mechines_cat { get; set; }
        public virtual User_list User_list { get; set; }
    }
}
