//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int IssueID { get; set; }
        public int Actual { get; set; }
        public int Target { get; set; }
        public int Required { get; set; }
        public int Product_name { get; set; }
        public int emp_id { get; set; }
        public string note { get; set; }
        public System.DateTime issued_time { get; set; }
    
        public virtual product_name product_name1 { get; set; }
        public virtual User_list User_list { get; set; }
    }
}
