//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_list()
        {
            this.Log_Tab = new HashSet<Log_Tab>();
            this.Material_process = new HashSet<Material_process>();
            this.Material_process1 = new HashSet<Material_process>();
            this.Mechine_status = new HashSet<Mechine_status>();
            this.MetaInfoes = new HashSet<MetaInfo>();
            this.MetaInfoes1 = new HashSet<MetaInfo>();
            this.products = new HashSet<product>();
            this.SocialLogs = new HashSet<SocialLog>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string SureName { get; set; }
        public int infor_ID { get; set; }
        public string boss_res { get; set; }
        public string staff_res { get; set; }
        public int session_ID { get; set; }
        public string Password { get; set; }
        public string imagepath { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string email { get; set; }
        public string username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log_Tab> Log_Tab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_process> Material_process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_process> Material_process1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mechine_status> Mechine_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetaInfo> MetaInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetaInfo> MetaInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialLog> SocialLogs { get; set; }
        public virtual staff staff { get; set; }
    }
}
